on: push
jobs:
  sleep:
    runs-on: ubuntu-latest
    environment: staging
    concurrency:
      group: "sleep"
    steps:
      - run: echo Step Before
      - run: sleep 300
      - run: echo Step After
  next:
    runs-on: ubuntu-latest
    concurrency:
      group: "next"
    needs: [sleep]
    steps:
      - run: echo Hello, World
